# Generated by Django 5.0.6 on 2024-06-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_question_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
