# Generated by Django 5.0.6 on 2024-07-07 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyCategoryModel",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="studymodel",
            name="is_video",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studymodel",
            name="video_uri",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studytopicmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="quiz.studycategorymodel",
            ),
        ),
    ]
