# Generated by Django 5.0.6 on 2024-07-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_studycategorymodel_studymodel_is_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="topic",
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.CharField(
                choices=[
                    ("Management of Care", "Management of Care"),
                    ("Safety and Infection Control", "Safety and Infection Control"),
                    (
                        "Health Promotion and Maintenance",
                        "Health Promotion and Maintenance",
                    ),
                    ("Psychosocial Integrity", "Psychosocial Integrity"),
                    ("Basic Care and Comfort", "Basic Care and Comfort"),
                    (
                        "Pharmacological and Parenteral Therapies",
                        "Pharmacological and Parenteral Therapies",
                    ),
                    ("Reduction of Risk Potential", "Reduction of Risk Potential"),
                    ("Physiological Adaptation", "Physiological Adaptation"),
                    ("Adult Health", "Adult Health"),
                    ("Child Health", "Child Health"),
                    ("Critical Care", "Critical Care"),
                    ("Fundamentals", "Fundamentals"),
                    ("Leadership & Management", "Leadership & Management"),
                    ("Maternal & Newborn Health", "Maternal & Newborn Health"),
                    ("Mental Health", "Mental Health"),
                    ("Pharmacology", "Pharmacology"),
                    ("Postpartum", "Postpartum"),
                    ("Prioritization", "Prioritization"),
                    ("Newborn", "Newborn"),
                    ("Assignment/Delegation", "Assignment/Delegation"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="duration",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="quiz",
            name="exam_mode",
            field=models.BooleanField(default=False),
        ),
    ]
