# Generated by Django 3.2 on 2024-07-29 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_topic_question_topic_quiz_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenquizquestions',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
