# Generated by Django 3.2 on 2024-07-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_givenquizquestions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenquizquestions',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_questions', to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='given_question',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.GivenQuizQuestions'),
        ),
    ]
