# Generated by Django 5.0.6 on 2024-08-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_usersubscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studymodel",
            name="video_uri",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
