# Generated by Django 5.0.6 on 2024-09-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_readinessassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isReadiness',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='READINESSASSESSMENT',
        ),
    ]
