# Generated by Django 5.0.6 on 2024-10-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_question_isreadiness_delete_readinessassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
