# Generated by Django 5.0.6 on 2024-09-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_question_isreadiness_delete_readinessassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_category",
                to="quiz.studycategorymodel",
            ),
        ),
    ]
