# Generated by Django 5.0.6 on 2024-10-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0015_answer_reason"),
        ("quiz", "0015_studymodel_category"),
    ]

    operations = []
