# Generated by Django 5.0.6 on 2025-04-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
