# Generated by Django 5.0.6 on 2025-04-08 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0019_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="answer",
            name="reason",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
