# Generated by Django 5.0.6 on 2025-04-16 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
