# Generated by Django 4.2.25 on 2025-10-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
