# Generated by Django 4.2.25 on 2026-02-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_userprofile_has_used_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='has_used_trial_for_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
