# Generated by Django 4.2.25 on 2026-02-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_usersubscription_has_used_trial_for_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='has_used_trial_for_plan',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
